// import { getServerSession } from "next-auth";
// import AboutContent from "../components/AboutContent";
// import { authOptions } from "../api/auth/[...nextauth]/route";
// export const dynamic = 'force-dynamic';

// export const metadata = {
//     title: "About",
//     description: "Generated by create next app",
//   };

  
//   export const getTime = async()=>{
//     const apiUrl = process.env.NEXT_PUBLIC_API_URL
//    const res = await  fetch(`${apiUrl}/api/time`,{next:{revalidate:5}})
//    const data = await res.json();
//    return data.currentTime;

// }
// const page = async() => {

//     const currentTime =await getTime();
//    const session =await getServerSession(authOptions);
// console.log({session})
//     return (
//         <div>
//             <AboutContent></AboutContent>
//             <h2 className="text-3xl">Time : {currentTime} </h2>
         
//         </div>
//     );
// };

// export default page;