import AboutContent from "../components/AboutContent";

export const metadata = {
    title: "About",
    description: "Generated by create next app",
  };
  export const getTime = async()=>{
    
   const res = await fetch("http://localhost:3000/time",{next:{revalidate:5}})
   const data = await res.json();
   return data.currentTime;

}
const page = async() => {
    const currentTime =await getTime();

    return (
        <div>
            <AboutContent></AboutContent>
            <h2 className="text-3xl">Time : {currentTime} </h2>
         
        </div>
    );
};

export default page;